#How to build the ROS/Gazebo bridges!

#1. Run your model in Gazebo, then run 'ros2 topic list' in the terminal
#2. You will now see the ROS topics your Gazebo model might want to publish to (e.g. joint_states) or subscribe to (e.g. cmd_vel)
#3. For each ROS topic you need to create a bridge for, now find its interface type using 'ros2 topic info /topic'
#4. Make note of both the topic and the interface type it uses
#5. Now use 'gz topic -l' in the terminal to get a list of the current Gazebo topics
#6. For each Gazebo topic you need to create a bridge for, now find its interface type using 'gz topic -i -t /topic'
#7. Again make note of the topics and the topic types you need to use...
#8. Now visit this page: https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge
#9. On this page you will find the corresponding gazebo topic type and ros topic type and here you can map them together!


#Always use these

- ros_topic_name: "/clock" #Ensures sim_time matches across the programs
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# REMOVED AS NOW HANDLED BY ROS2_CONTROL JOINT STATE CONTROLLER, NOT GAZEBO PLUGIN

# - ros_topic_name: "/joint_states"  #gz topic published by JointState plugin
#   gz_topic_name: "/joint_states"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS


#==============================================


#Use if a mobile base you want to control

# ALL REMOVED AS NOW HANDLED BY ROS2_CONTROL DIFF-DRIVE CONTROLLER, NOT GAZEBO DIFF-DRIVE PLUGIN

# - ros_topic_name: "/cmd_vel" #gz topic published by DiffDrive plugin
#   gz_topic_name: "/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ

- ros_topic_name: "/odom" #gz topic published by DiffDrive plugin
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS


#==============================================

# THESE ARE LEFT IN, AS STILL HANDLED BY GAZEBO PLUGINS

#Used for lidar
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  lazy: false

#Used for camera
- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

#Used for IMU
- ros_topic_name: "imu/data"
  gz_topic_name: "imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  lazy: false