#!/usr/bin/env python3
"""
Launch file to run the map_saver_cli node.

This launch file provides a convenient way to save the map generated by a SLAM node
directly into the 'maps' directory of the slambot_slam package. It listens to a
namespaced map topic for multi-robot compatibility.
"""
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node


def generate_launch_description():
    """Generate the launch description to save the map."""

    # --- New Launch Argument for Map Save Directory ---
    # We will use this to save to a *writable* path like the source directory.
    # We can default it to a common temporary location to prevent the install-folder error.
    declare_save_dir_cmd = DeclareLaunchArgument(
        'map_save_dir',
        default_value=os.path.join(os.environ['HOME'], 'nav2_maps'), # Default to a safe, writable folder in your home directory
        description='The directory where the map will be saved'
    )

    # --- Declare Launch Arguments ---
    declare_map_name_cmd = DeclareLaunchArgument(
        'map_name',
        default_value='saved_map',
        description='The name of the map file to save (without extension)'
    )


    # Construct the full path where the map file will be saved
    # NOW we use the LaunchConfiguration('map_save_dir') for the base path
    map_file_path = PathJoinSubstitution([
        LaunchConfiguration('map_save_dir'), # Using the new argument
        LaunchConfiguration('map_name')
    ])


    # --- Map Saver Node ---
    # This node runs the map_saver_cli tool from the nav2_map_server package
    save_map_node = Node(
        package='nav2_map_server',
        executable='map_saver_cli',
        output='screen',
        arguments=[
            '-t', '/map',
            '-f', map_file_path
        ],
        parameters=[{'use_sim_time': True}], # Important for simulation environments
    )


    # --- Create Launch Description ---
    ld = LaunchDescription()

    # Add the declared arguments and the node to the launch description
    ld.add_action(declare_save_dir_cmd)
    ld.add_action(declare_map_name_cmd)
    ld.add_action(save_map_node)

    return ld

