camera:
  ros__parameters:
    camera: 0              # Index 0 is the first available camera (even if on port 1)
    width: 640             # 640x480 is ideal for SLAM (balance of speed/quality)
    height: 480
    format: "YUYV"         # Faster than RGB for the pi to process
    frame_id: "camera_1" # IMPORTANT: Must match the link name in your URDF