controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    # imu_sensor_broadcaster:
    #   type: imu_sensor_broadcaster/IMUSensorBroadcaster


diff_drive_controller:
  ros__parameters:

    # -----------------------------
    # WHEELS
    # -----------------------------
    left_wheel_names: ["rear_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint",]

    wheel_separation: 0.42
    wheel_radius: 0.075

    wheels_per_side: 1

    # -----------------------------
    # FEEDBACK
    # -----------------------------
    position_feedback: true
    open_loop: false

    # -----------------------------
    # CMD_VEL
    # -----------------------------
    use_stamped_vel: true
    cmd_vel_timeout: 0.5

    # -----------------------------
    # ODOM
    # -----------------------------
    publish_rate: 100.0

    base_frame_id: base_footprint
    odom_frame_id: odom

    enable_odom_tf: false

    velocity_rolling_window_size: 10

    # -----------------------------
    # LINEAR LIMITS
    # -----------------------------
    linear.x:
      has_velocity_limits: true
      max_velocity: 1.0
      min_velocity: -1.0

      has_acceleration_limits: true
      max_acceleration: 1.8
      min_acceleration: -1.8

      has_jerk_limits: false

    # -----------------------------
    # ANGULAR LIMITS
    # -----------------------------
    angular.z:
      has_velocity_limits: true
      max_velocity: 2.5
      min_velocity: -2.5

      has_acceleration_limits: true
      max_acceleration: 3.5
      min_acceleration: -3.5

      has_jerk_limits: false

    # -----------------------------
    # NAV2 / EKF STABILITY
    # -----------------------------
    pose_covariance_diagonal:
      [0.001, 0.001, 1000000.0,
       1000000.0, 1000000.0, 0.03]

    twist_covariance_diagonal:
      [0.001, 0.001, 1000000.0,
       1000000.0, 1000000.0, 0.03]


# imu_sensor_broadcaster:
#   ros__parameters:
#     sensor_name: imu_sensor
#     frame_id: imu_link_1            